name: nested
description: A Flutter Widget which helps nest multiple widgets without needing to manually nest them.
version: 0.0.4
author: Remi Rousselet <darky12s@gmail.com>
homepage: https://github.com/rrousselGit/nested

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter_web: any

dev_dependencies:
  flutter_web_test: any
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0

  test: ^1.3.4

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test